import type { Metadata } from "next";
import NavBar from "./_component/Navbar";
import "./globals.css";

 
export const metadata: Metadata = {
  title: "Next JS By JK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"    >
      <body className="min-h-screen bg-gray-50">
        <NavBar />
        <main className="container mx-auto px-4 py-8">
            {children}
        </main>
      </body>
    </html>
  );
}
